#!/bin/bash

usage="rtest <servurl> <platform> <arch> <srcfile> <expectedsize> ==> OK/ERROR"


if [ "$#" == "5" ]; then
    rm -f binary.zip
	./rfaust $1 $2 $3 $4 2> /dev/null
    maxsize=$5
    filesize=$(du -k "binary.zip" | cut -f1)
    filesize=$(( 1024*filesize ))

    if (( filesize > maxsize )); then
        echo "rtest $1 $2 $3 $4 $filesize:  OK"
    else
        echo "rtest $1 $2 $3 $4 $filesize:  ERROR"
    fi
else
    echo "usage: $usage"
fi 

