#!/bin/bash

# Enviroment variable that can be set a default faustservice url
[ ! -z "$1" ] && SERVICE="$1" || SERVICE=${CLOUDSERVICE:="https://faustservicecloud.grame.fr"}

PLATFORM=web

./rtest $SERVICE $PLATFORM pwa kisana.dsp 4000
./rtest $SERVICE $PLATFORM pwa-poly kisana.dsp 4000
./rtest $SERVICE $PLATFORM wam2-fft-ts kisana.dsp 600000
./rtest $SERVICE $PLATFORM wam2-poly-ts kisana.dsp 600000
./rtest $SERVICE $PLATFORM wam2-ts kisana.dsp 600000
./rtest $SERVICE $PLATFORM wasmjs kisana.dsp 130000
./rtest $SERVICE $PLATFORM wasmjs-poly kisana.dsp 130000
./rtest $SERVICE $PLATFORM webaudiowasm kisana.dsp 180000
./rtest $SERVICE $PLATFORM webaudiowasm-poly kisana.dsp 180000
