#!/bin/bash

# Enviroment variable that can be set a default faustservice url
[ ! -z "$1" ] && SERVICE="$1" || SERVICE=${CLOUDSERVICE:="https://faustservicecloud.grame.fr"}

./rtest $SERVICE "julia" "julia" kisana.dsp 12000
./rtest $SERVICE "julia" "portaudiojulia" kisana.dsp 16000
