#!/bin/bash

# Enviroment variable that can be set a default faustservice url
[ ! -z "$1" ] && SERVICE="$1" || SERVICE=${CLOUDSERVICE:="https://faustservicecloud.grame.fr"}

PLATFORM=source
ARCHLIST="any api-android api-ios api-poly-android api-poly-ios c chaos-stratus cplusplus juce juce-poly julia smartkeyb-android smartkeyb-ios"

for ARCH in $ARCHLIST; do
    ./rtest $SERVICE $PLATFORM $ARCH kisana.dsp 10000
done
