#!/bin/bash

# Enviroment variable that can be set a default faustservice url
[ ! -z "$1" ] && SERVICE="$1" || SERVICE=${CLOUDSERVICE:="https://faustservicecloud.grame.fr"}

PLATFORM=rnbo
ARCHLIST="rnbo rnbo-poly rnbo-poly-effect"

for ARCH in $ARCHLIST; do
	./rtest $SERVICE $PLATFORM $ARCH kisana.dsp 10000
done
