#!/bin/bash

# Enviroment variable that can be set a default faustservice url
[ ! -z "$1" ] && SERVICE="$1" || SERVICE=${CLOUDSERVICE:="https://faustservicecloud.grame.fr"}

PLATFORM=unity
#ARCHLIST="android ios linux osx source windows32 windows64"
ARCHLIST="source linux windows32 windows64"

for ARCH in $ARCHLIST; do
    ./rtest $SERVICE $PLATFORM $ARCH kisana.dsp 50000
done