#!/bin/bash

# Enviroment variable that can be set a default faustservice url
[ ! -z "$1" ] && SERVICE="$1" || SERVICE=${CLOUDSERVICE:="https://faustservicecloud.grame.fr"}

PLATFORM=android
ARCHLIST="android android-osc smartkeyb"

for ARCH in $ARCHLIST; do
	./rtest $SERVICE $PLATFORM $ARCH kisana.dsp 1732000
done