#!/bin/bash

# Enviroment variable that can be set a default faustservice url
[ ! -z "$1" ] && SERVICE="$1" || SERVICE=${CLOUDSERVICE:="https://faustservicecloud.grame.fr"}

PLATFORM=osx
ARCHLIST="coreaudio-qt coreaudio-qt-midi csound jack-qt max plot puredata puredata-poly supercollider vst vsti"

for ARCH in $ARCHLIST; do
	[ -d kisana.app ] && rm -rf kisana.app
	./rtest $SERVICE $PLATFORM $ARCH kisana.dsp 14000
done