#!/bin/bash

# Enviroment variable that can be set a default faustservice url
[ ! -z "$1" ] && SERVICE="$1" || SERVICE=${CLOUDSERVICE:="https://faustservicecloud.grame.fr"}

PLATFORM=source
ARCHLIST="api-android api-ios api-poly-android api-poly-ios juce juce-poly"

for ARCH in $ARCHLIST; do
	./rtest $SERVICE $PLATFORM $ARCH kisana.dsp 150000
done



./rtest $SERVICE $PLATFORM cplusplus kisana.dsp 9800
./rtest $SERVICE $PLATFORM smartkeyb-android kisana.dsp 500000
./rtest $SERVICE $PLATFORM smartkeyb-ios kisana.dsp 400000
