#!/bin/bash

# Enviroment variable that can be set a default faustservice url
[ ! -z "$1" ] && SERVICE="$1" || SERVICE=${CLOUDSERVICE:="https://faustservicecloud.grame.fr"}

PLATFORM=vcvrack
ARCHLIST="vcvrack vcvrack-poly16 vcvrack-poly8"

for ARCH in $ARCHLIST; do
    ./rtest $SERVICE $PLATFORM $ARCH kisana.dsp 600000
done
