#!/bin/bash

# Enviroment variable that can be set a default faustservice url
[ ! -z "$1" ] && SERVICE="$1" || SERVICE=${CLOUDSERVICE:="https://faustservicecloud.grame.fr"}

PLATFORM=web

./rtest $SERVICE $PLATFORM wam2-fft-ts kisana.dsp 88100
./rtest $SERVICE $PLATFORM wam2-poly-ts kisana.dsp 88100
./rtest $SERVICE $PLATFORM wam2-ts kisana.dsp 88100
./rtest $SERVICE $PLATFORM wasmjs-poly-ts kisana.dsp 88100
./rtest $SERVICE $PLATFORM wasmjs-ts kisana.dsp 88100
./rtest $SERVICE $PLATFORM webaudiowasm-poly-ts kisana.dsp 88100
./rtest $SERVICE $PLATFORM webaudiowasm-ts kisana.dsp 88100